[package]
name = "transcendent-table-tennis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.17.0"
legion = "0.4.0"
macroquad = "0.3"
rand = "0.8.5"
